name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.14.0'
    - name: Install Application Dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install Test Dependencies
      run: cd EcommercePlaywrightTests && npm install
    - name: Run Playwright Tests
      run: cd EcommercePlaywrightTests && npx playwright test
    - name: Run Cucumber API Tests
      run: cd EcommerceApiTests && npm test
